
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- MAQUILLAJE Y NOVEDADES 2026 ---
    { id: 47188, name: "Iluminador Líquido Illuskin THE ONE", brand: "The ONE", price: 8.46, regularPrice: 20.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47188%2F47188_1.png", description: "Iluminador líquido versátil para un brillo natural o intenso. Mezclable y modulable.", stock: 50, category: "makeup", tag: "NOVEDAD", rating: 4.7, reviewCount: 54 },
    { id: 46134, name: "BB Cream Beautifier MAX THE ONE", brand: "The ONE", price: 5.77, regularPrice: 17.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46134%2F46134_1.png", description: "BB Cream multifuncional que hidrata, corrige y protege. Acabado natural.", stock: 289, category: "makeup", tag: "NOVEDAD", rating: 4.8, reviewCount: 142 },
    { id: 46901, name: "Perlas con Serum Giordani Gold", brand: "Giordani Gold", price: 16.93, regularPrice: 35.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png", description: "Perlas bronceadoras infusionadas con serum antiedad. Edición limitada.", stock: 50, category: "makeup", tag: "NOVEDAD", rating: 4.9 },

    // --- PERFUMERÍA LUXE (NUEVOS) ---
    { id: 38521, name: "Eclat Mon Parfum", brand: "Eclat", price: 34.99, regularPrice: 52.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F33957%2F33957_1.png", description: "La expresión máxima de la elegancia francesa con el exclusivo acorde DeLaire.", stock: 25, category: "perfume", tag: "OFERTA", rating: 4.9, reviewCount: 210 },
    { id: 30886, name: "Possess Eau de Parfum", brand: "Possess", price: 31.99, regularPrice: 48.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F30886%2F30886_1.png", description: "Aroma atemporal, potente y cautivador inspirado en Cleopatra.", stock: 40, category: "perfume", rating: 4.8, reviewCount: 340 },
    { id: 42502, name: "GG Essenza Blossom Parfum", brand: "Giordani Gold", price: 39.99, regularPrice: 60.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38534%2F38534_1.png", description: "Una joya de la perfumería con notas de Azahar y Camelia.", stock: 15, category: "perfume", tag: "NOVEDAD", rating: 5.0 },
    { id: 42751, name: "Love Potion Sensual Ruby", brand: "Love Potion", price: 24.99, regularPrice: 38.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40691%2F40691_1.png", description: "Chocolate rubí y bayas rojas para una seducción total.", stock: 30, category: "perfume", rating: 4.7 },
    { id: 35649, name: "All or Nothing Parfum", brand: "All or Nothing", price: 44.99, regularPrice: 65.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F35679%2F35679_1.png", description: "Vainilla Surabsolute pura. Tu esencia, tus reglas.", stock: 12, category: "perfume", rating: 4.9 },
    { id: 42813, name: "Nordic Waters for Her", brand: "Oriflame", price: 27.99, regularPrice: 42.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43122%2F43122_1.png", description: "La frescura vibrante de los mares nórdicos.", stock: 45, category: "perfume", tag: "NOVEDAD" },

    // --- COFRES Y SETS DE REGALO (NUEVOS) ---
    { id: 99001, name: "Cofre Regalo Novage+ Brilliance", brand: "Novage+", price: 89.00, regularPrice: 145.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45595%2F45595_1.png", description: "Set completo antimanchas y luminosidad en caja de lujo.", stock: 20, category: "skincare", tag: "SET", rating: 5.0 },
    { id: 99002, name: "Cofre Amber Elixir + Bruma", brand: "Amber Elixir", price: 29.99, regularPrice: 45.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46805%2F46805_1.png", description: "Perfume icónico y bruma corporal coordinada en caja premium.", stock: 50, category: "perfume", tag: "SET" },
    { id: 48675, name: "Caja de Regalo Turquesa Crema Universal", brand: "Oriflame", price: 13.85, regularPrice: 36.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48675%2F48675_1.png", description: "El regalo perfecto: Trío de cremas universales icónicas.", stock: 100, category: "skincare", tag: "SET" },

    // --- CREMAS CORPORALES PERFUMADAS (NUEVOS) ---
    { id: 42921, name: "Crema Corporal Giordani Gold", brand: "Giordani Gold", price: 8.99, regularPrice: 14.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42907%2F42907_1.png", description: "Hidratación profunda con el aroma floral blanco de Giordani Gold.", stock: 100, category: "personal-care", rating: 4.9 },
    { id: 42922, name: "Crema Corporal Possess", brand: "Possess", price: 8.99, regularPrice: 14.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42908%2F42908_1.png", description: "Piel suave y perfumada con notas de Ylang Ylang.", stock: 80, category: "personal-care", rating: 4.8 },
    { id: 42923, name: "Crema Corporal Love Potion", brand: "Love Potion", price: 8.99, regularPrice: 14.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42909%2F42909_1.png", description: "Textura rica con aroma a jengibre y cacao.", stock: 90, category: "personal-care" },

    // --- DESODORANTES Y COMPLEMENTOS (NUEVOS) ---
    { id: 42521, name: "Roll-On Perfumado Eclat Femme", brand: "Eclat", price: 4.49, regularPrice: 8.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41542%2F41542_1.png", description: "Protección eficaz con la elegancia de Eclat.", stock: 200, category: "personal-care" },
    { id: 42522, name: "Roll-On Perfumado Giordani Gold Man", brand: "Giordani Gold", price: 4.49, regularPrice: 8.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41293%2F41293_1.png", description: "Frescura masculina con notas amaderadas.", stock: 180, category: "men" },
    { id: 42523, name: "Roll-On Perfumado Divine", brand: "Divine", price: 4.49, regularPrice: 8.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41300%2F41300_1.png", description: "Fragancia celestial para tu día a día.", stock: 220, category: "personal-care" },
    { id: 42524, name: "Spray Corporal Soul", brand: "Soul", price: 9.99, regularPrice: 15.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42504%2F42504_1.png", description: "Energía cítrica en spray para el hombre activo.", stock: 95, category: "men" },

    // --- MÁS PERFUMERÍA Y CUIDADO ---
    { id: 31297, name: "Eclat Homme Eau de Toilette", brand: "Eclat", price: 26.99, regularPrice: 40.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F30173%2F30173_1.png", description: "Sofisticación moderna para el hombre de hoy.", stock: 55, category: "men" },
    { id: 38497, name: "Divine Eau de Parfum", brand: "Divine", price: 26.99, regularPrice: 45.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2FES%2F38497_1.png", description: "Elegancia pura con notas de Orquídea.", stock: 40, category: "perfume", tag: "OFERTA" },
    { id: 46642, name: "Jabón Líquido Limón y Verbena", brand: "Essense & Co", price: 15.99, regularPrice: 20.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46642%2F46642_1.png", description: "Lujo botánico para manos y cuerpo.", stock: 30, category: "personal-care" },
    { id: 41338, name: "Crema de Manos Coco Orgánico", brand: "Love Nature", price: 2.99, regularPrice: 11.00, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41338%2FES%2F41338_1.png", description: "Nutrición intensa con aroma tropical.", stock: 50, category: "personal-care", tag: "OFERTA" }
];
